version: '3'

services:
  bot1:
    build: .
    volumes:
      - ./bot1:/app/ProfitTrailer
    restart: always
    ports:
      - "8081:8081/tcp"
#  bot2:
#    build: .
#    volumes:
#      - ./bot2:/app/ProfitTrailer
#    restart: always
#    ports:
#      - "8081:8081/tcp"
