# Default values for profit-trailer.
# Values that are have values equal - means that the name will be the concatenation of exchange, market and bot id
# Ingress example:
# exchange-market-environment-botId => binance-btc-prod-01-ingress

# Default namespace
namespace: profit-trailer
# Application name
app: profit-trailer
# Bot id
botId: "001"
# Exchange being used by the bot
exchange: binance
# Market being used by the bot
market: btc
# Environment that the bot is running
environment: test

# SSL certificate
certificate:
  # Indicates if issuer is ClusterIssuer or Issuer (namespaced)
  issuer: "ClusterIssuer"
  # SSL certificate for staging, to be used while testing. Possible values are production,staging
  env: staging
  # The email address that should receive emails from Lets Encrypt
  email: email@dot.com

# Service to expose the port
service:
  # Service name, change - to override the name.
  name: "-"

# Statefulset to deploy the application
statefulset:
  # Statefulset name, change - to override the name.
  name: "-"

# Ingress used to expose the application outside
ingress:
  # Name of the ingress, change - to override the name.
  name: "-"
  # Ingress class used by K8s
  class: nginx
  # Domain used to access the bot, this domain must exist in order for Lets Encrypt to work
  host: profit-trailer.domain.com
    
containers:
  # Container image for Profit Trailer
  image: lucasconde/profit-trailer:2.5.46
resources: 
  # Minimum requirements for Profit Trailer to run
  requests:
    cpu: 200m
    memory: 512Mi
  # Maximum resources for Profit Trailer, setting more than the bot itself to have spare room
  limits:
    cpu: 700m
    memory: 1024Mi

# Define is node affinity should be set
useNodeAffinity: false 
nodeAffinity:
  key: kubernetes.io/hostname
  values: 
  #  - value.1
  #  - value.2

# Volume claim to be used
volumeClaim:
  # Define the storage class to be used when creating the PVC
  storageClassName: 
    data: longhorn-pt
    log: longhorn
  # Size of the storage that will be allocated
  requests:
    dataStorage: 2Gi
    logStorage: 2Gi